# -*- coding: utf-8 -*-
"""
동글랜드 허용 모드 카탈로그
출처: https://dongle-land.gitbook.io/dongle_land/info/connect

각 항목 설명
-----------
id               : 내부 식별자 (레지스트리 키로 사용)
name             : 표시 이름
slug             : Modrinth 슬러그 (None 이면 Modrinth 미사용)
bundled_asset    : exe 내 assets/ 에 번들된 파일명
category         : 필수 / 최적화 / 시각 / 지도 / 사운드 / 한글 / 편의
required         : True 이면 제거 불가 (필수 모드)
tags             : 화면 태그
description      : 한국어 설명
exclusive_group  : 동일 그룹 내 1개만 설치 가능
dependencies     : 자동 함께 설치할 mod id 목록
hidden           : True 이면 목록 미표시 (종속 전용)
"""

GAME_VERSION = "26.1.2"
LOADER = "fabric"

MODS = [
    # ── 필수 ─────────────────────────────────────────────────────────────
    {
        "id": "modcheckclient",
        "name": "ModCheck Client",
        "slug": None,
        "bundled_asset": "modcheckclient-1.2.0.jar",
        "category": "필수",
        "required": True,
        "tags": ["필수"],
        "description": "동글랜드 서버 전용 모드 체크 클라이언트입니다.\n서버 접속 시 허용된 모드만 설치되어 있는지 검증합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "fabric-api",
        "name": "Fabric API",
        "slug": "fabric-api",
        "bundled_asset": None,
        "category": "필수",
        "required": True,
        "tags": ["필수"],
        "description": "Fabric 모드 로더의 핵심 라이브러리입니다.\n대부분의 Fabric 모드가 동작하는 데 필요합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },

    # ── 최적화 ───────────────────────────────────────────────────────────
    {
        "id": "sodium",
        "name": "Sodium",
        "slug": "sodium",
        "bundled_asset": None,
        "category": "최적화",
        "required": False,
        "tags": ["최적화"],
        "description": "마인크래프트 렌더링 엔진을 전면 재작성해 FPS를 크게 향상시킵니다.\n대부분의 환경에서 즉시 체감되는 성능 향상을 제공합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "lithium",
        "name": "Lithium",
        "slug": "lithium",
        "bundled_asset": None,
        "category": "최적화",
        "required": False,
        "tags": ["최적화"],
        "description": "게임 로직 및 서버 틱 성능을 최적화합니다.\n게임플레이 변경 없이 전반적인 성능을 향상시킵니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "ferrite-core",
        "name": "FerriteCore",
        "slug": "ferrite-core",
        "bundled_asset": None,
        "category": "최적화",
        "required": False,
        "tags": ["최적화"],
        "description": "마인크래프트의 메모리 사용량을 크게 줄여주는 최적화 모드입니다.\n램 사용량을 최대 50% 이상 절감할 수 있습니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "entityculling",
        "name": "EntityCulling",
        "slug": "entityculling",
        "bundled_asset": None,
        "category": "최적화",
        "required": False,
        "tags": ["최적화"],
        "description": "비동기 처리로 화면에 보이지 않는 엔티티·블록을 렌더링에서 제외해 FPS를 향상시킵니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "badoptimizations",
        "name": "BadOptimizations",
        "slug": "badoptimizations",
        "bundled_asset": None,
        "category": "최적화",
        "required": False,
        "tags": ["최적화"],
        "description": "다양한 소규모 최적화 패치를 모아놓은 경량 성능 개선 모드입니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "krypton",
        "name": "Krypton",
        "slug": "krypton",
        "bundled_asset": None,
        "category": "최적화",
        "required": False,
        "tags": ["최적화"],
        "description": "마인크래프트 네트워크 스택을 최적화합니다.\n서버 접속 안정성과 멀티플레이 성능을 향상시킵니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "moreculling",
        "name": "MoreCulling",
        "slug": "moreculling",
        "bundled_asset": None,
        "category": "최적화",
        "required": False,
        "tags": ["최적화"],
        "description": "EntityCulling보다 더 많은 요소를 culling하여 추가적인 FPS 향상을 제공합니다.\n(설치 시 Cloth Config API 자동 설치)",
        "exclusive_group": None,
        "dependencies": ["cloth-config"],
        "hidden": False,
    },
    {
        "id": "scalablelux",
        "name": "ScalableLux",
        "slug": "scalablelux",
        "bundled_asset": None,
        "category": "최적화",
        "required": False,
        "tags": ["최적화"],
        "description": "조명(라이팅) 시스템을 최적화하여 청크 로딩과 렌더링 성능을 향상시킵니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "dynamic-fps",
        "name": "Dynamic FPS",
        "slug": "dynamic-fps",
        "bundled_asset": None,
        "category": "최적화",
        "required": False,
        "tags": ["최적화"],
        "description": "마인크래프트가 백그라운드에 있거나 최소화됐을 때 FPS를 자동으로 제한해 CPU/GPU 자원 낭비를 줄입니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },

    # ── 시각 ─────────────────────────────────────────────────────────────
    {
        "id": "iris",
        "name": "Iris Shaders",
        "slug": "iris",
        "bundled_asset": None,
        "category": "시각",
        "required": False,
        "tags": ["시각", "셰이더"],
        "description": "OptiFine 셰이더팩을 Fabric 환경에서 사용할 수 있게 해주는 모드입니다.\nSodium과 함께 동작합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "wi-zoom",
        "name": "WI Zoom",
        "slug": "wi-zoom",
        "bundled_asset": None,
        "category": "시각",
        "required": False,
        "tags": ["시각", "줌"],
        "description": "최대 50배 줌을 지원하는 줌 기능 모드입니다.\n부드러운 카메라 이동과 함께 원거리 시야를 제공합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "entity-texture-features",
        "name": "Entity Texture Features",
        "slug": "entitytexturefeatures",
        "bundled_asset": None,
        "category": "시각",
        "required": False,
        "tags": ["시각", "텍스처"],
        "description": "엔티티의 텍스처를 다양화하고 개선합니다. 동일한 몬스터도 서로 다른 외형으로 나타납니다.\nEntity Model Features의 필수 종속 모드입니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "entity-model-features",
        "name": "Entity Model Features",
        "slug": "entity-model-features",
        "bundled_asset": None,
        "category": "시각",
        "required": False,
        "tags": ["시각", "모델"],
        "description": "CEM(Custom Entity Models) 형식의 커스텀 엔티티 모델을 지원합니다.\nOptiFine 리소스팩의 커스텀 몬스터 모델을 사용할 수 있습니다.\n(종속: Entity Texture Features 자동 설치)",
        "exclusive_group": None,
        "dependencies": ["entity-texture-features"],
        "hidden": False,
    },
    {
        "id": "sodium-extra",
        "name": "Sodium Extra",
        "slug": "sodium-extra",
        "bundled_asset": None,
        "category": "시각",
        "required": False,
        "tags": ["시각", "설정"],
        "description": "Sodium에서 제공하지 않는 추가 시각 설정 옵션을 제공합니다.\n파티클, 날씨, 애니메이션 등 세부 조절이 가능합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "continuity",
        "name": "Continuity",
        "slug": "continuity",
        "bundled_asset": None,
        "category": "시각",
        "required": False,
        "tags": ["시각", "텍스처"],
        "description": "유리, 조각돌 등 블록의 텍스처가 이어지는 연결 텍스처(CTM) 기능을 제공합니다.\nOptiFine 리소스팩 호환성을 높여줍니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },

    # ── 사운드 / 파티클 ───────────────────────────────────────────────────
    {
        "id": "simple-voice-chat",
        "name": "Simple Voice Chat",
        "slug": "simple-voice-chat",
        "bundled_asset": None,
        "category": "사운드",
        "required": False,
        "tags": ["사운드", "멀티"],
        "description": "마인크래프트에 근접 음성 채팅 기능을 추가합니다.\n같은 모드를 설치한 플레이어끼리 인게임에서 음성으로 소통할 수 있습니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "ambientsounds",
        "name": "AmbientSounds",
        "slug": "ambientsounds",
        "bundled_asset": None,
        "category": "사운드",
        "required": False,
        "tags": ["사운드", "환경"],
        "description": "바이옴과 환경에 어울리는 다채로운 주변 환경음을 추가합니다.\n(설치 시 CreativeCore 자동 설치)",
        "exclusive_group": None,
        "dependencies": ["creativecore"],
        "hidden": False,
    },
    {
        "id": "creativecore",
        "name": "CreativeCore",
        "slug": "creativecore",
        "bundled_asset": None,
        "category": "사운드",
        "required": False,
        "tags": ["라이브러리"],
        "description": "AmbientSounds의 필수 종속 라이브러리 모드입니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": True,
    },
    {
        "id": "sound-physics-remastered",
        "name": "Sound Physics Remastered",
        "slug": "sound-physics-remastered",
        "bundled_asset": None,
        "category": "사운드",
        "required": False,
        "tags": ["사운드"],
        "description": "블록을 통한 현실적인 소리 감쇠, 잔향, 흡수를 구현합니다.\n공간감 있는 사운드로 몰입도를 높여줍니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "presence-footsteps",
        "name": "Presence Footsteps",
        "slug": "presence-footsteps",
        "bundled_asset": None,
        "category": "사운드",
        "required": False,
        "tags": ["사운드"],
        "description": "걷는 블록 재질에 따라 다양한 발소리를 재생하는 몰입감 있는 사운드 모드입니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "particle-rain",
        "name": "Particle Rain",
        "slug": "particle-rain",
        "bundled_asset": None,
        "category": "사운드",
        "required": False,
        "tags": ["파티클", "날씨"],
        "description": "비, 눈 등 날씨 효과를 아름다운 파티클로 대체합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "subtle-effects",
        "name": "Subtle Effects",
        "slug": "subtle-effects",
        "bundled_asset": None,
        "category": "사운드",
        "required": False,
        "tags": ["파티클", "효과"],
        "description": "파티클과 소리를 통해 게임 곳곳에 미묘한 시각·청각 효과를 추가합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "coolrain",
        "name": "CoolRain",
        "slug": "coolrain",
        "bundled_asset": None,
        "category": "사운드",
        "required": False,
        "tags": ["사운드", "날씨"],
        "description": "비 내리는 소리와 빗방울 효과를 훨씬 더 실감나게 개선합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "extreme-sound-muffler",
        "name": "Extreme Sound Muffler",
        "slug": "extreme_sound_muffler",
        "bundled_asset": None,
        "category": "사운드",
        "required": False,
        "tags": ["사운드"],
        "description": "특정 소리의 볼륨을 개별적으로 조절하거나 완전히 음소거할 수 있습니다.\n시끄러운 환경음이나 특정 효과음을 선별적으로 차단할 수 있습니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },

    # ── 지도 ─────────────────────────────────────────────────────────────
    {
        "id": "xaeros-minimap",
        "name": "Xaero's Minimap",
        "slug": "xaeros-minimap",
        "bundled_asset": None,
        "category": "지도",
        "required": False,
        "tags": ["지도"],
        "description": "화면 모서리에 실시간 미니맵을 표시해주는 모드입니다.\n웨이포인트 설정과 좌표 표시 기능을 포함합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "xaeros-world-map",
        "name": "Xaero's World Map",
        "slug": "xaeros-world-map",
        "bundled_asset": None,
        "category": "지도",
        "required": False,
        "tags": ["지도"],
        "description": "탐험한 전체 월드를 지도로 확인할 수 있는 세계 지도 모드입니다.\nXaero's Minimap과 함께 사용하면 더욱 좋습니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "journeymap",
        "name": "JourneyMap",
        "slug": "journeymap",
        "bundled_asset": None,
        "category": "지도",
        "required": False,
        "tags": ["지도"],
        "description": "실시간 미니맵과 풀스크린 지도를 제공합니다.\n웹 브라우저에서도 지도를 확인할 수 있습니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },

    # ── 한글 (둘 중 하나만 설치 가능) ──────────────────────────────────
    {
        "id": "koreanify",
        "name": "Koreanify",
        "slug": "koreanify",
        "bundled_asset": None,
        "category": "한글",
        "required": False,
        "tags": ["한글"],
        "description": "마인크래프트 채팅창에서 한글 입력 시 발생하는 버그를 수정합니다.\nimblocker와 동시에 설치할 수 없습니다.",
        "exclusive_group": "korean",
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "imblocker",
        "name": "imblocker",
        "slug": "imblocker-original",
        "bundled_asset": None,
        "category": "한글",
        "required": False,
        "tags": ["한글"],
        "description": "텍스트 입력 시 IME(입력기)를 숨겨 한글 입력 버그를 해결합니다.\nKoreanify와 동시에 설치할 수 없습니다.",
        "exclusive_group": "korean",
        "dependencies": [],
        "hidden": False,
    },

    # ── 편의 ─────────────────────────────────────────────────────────────
    {
        "id": "modmenu",
        "name": "Mod Menu",
        "slug": "modmenu",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "UI"],
        "description": "게임 내에서 설치된 모드 목록을 확인하고 설정을 변경할 수 있는 메뉴를 추가합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "placeholder-api",
        "name": "Text Placeholder API",
        "slug": "placeholder-api",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "라이브러리"],
        "description": "텍스트 플레이스홀더 기능을 제공하는 라이브러리 모드입니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "punchy-fpa",
        "name": "Punchy!",
        "slug": "punchy-fpa",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "애니메이션"],
        "description": "다양한 1인칭 손 애니메이션과 아이템을 든 손 동작을 추가하는 모드입니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "cloth-config",
        "name": "Cloth Config API",
        "slug": "cloth-config",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "라이브러리"],
        "description": "다양한 모드의 설정 화면(Config GUI)을 지원하는 공통 설정 API 라이브러리입니다.\nBetterF3, Sodium Extra 등 여러 모드가 필요로 합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "betterf3",
        "name": "BetterF3",
        "slug": "betterf3",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "UI"],
        "description": "F3 디버그 화면을 색상 구분과 모듈화로 읽기 쉽게 개선합니다.\n(종속: Cloth Config API 자동 설치)",
        "exclusive_group": None,
        "dependencies": ["cloth-config"],
        "hidden": False,
    },
    {
        "id": "inventoryhud",
        "name": "InventoryHUD+",
        "slug": "inventoryhudplus",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "HUD"],
        "description": "인벤토리, 갑옷, 장비 내구도를 화면에 실시간으로 표시해줍니다.\n전투 중 빠르게 상태를 확인할 수 있습니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "chatpatches",
        "name": "Chat Patches",
        "slug": "chatpatches",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "채팅"],
        "description": "채팅 기능을 다양하게 개선합니다.\n채팅 히스토리, 복사, 멘션 하이라이트 등을 지원합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "jade",
        "name": "Jade",
        "slug": "jade",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "UI"],
        "description": "블록과 엔티티에 마우스를 올리면 이름, 체력, 데이터 등 상세 정보를 화면에 표시해줍니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "borderless-fullscreen",
        "name": "Borderless Fullscreen",
        "slug": "borderless-fullscreen",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의"],
        "description": "마인크래프트를 테두리 없는 창 모드(Borderless Windowed)로 실행합니다.\n다른 창으로 빠르게 전환할 수 있습니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "server-pack-unlocker",
        "name": "Server Pack Unlocker",
        "slug": "server-pack-unlocker",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의"],
        "description": "서버에서 강제 적용하는 리소스팩을 선택적으로 사용하거나 해제할 수 있습니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "scoreboardtweaks",
        "name": "ScoreboardTweaks",
        "slug": "scoreboardtweaks",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "UI"],
        "description": "스코어보드의 표시 방식을 개선하고 숨기기, 위치 조정 등을 커스터마이징합니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "shulkerboxtooltip",
        "name": "Shulker Box Tooltip",
        "slug": "shulkerboxtooltip",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "UI"],
        "description": "슐커 박스 아이템 위에 마우스를 올리면 내용물을 미리 볼 수 있습니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "replaymod",
        "name": "ReplayMod",
        "slug": "replaymod",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "녹화"],
        "description": "게임 플레이를 녹화하고 나중에 자유 시점으로 재생하거나 고품질 영상을 제작할 수 있습니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
    {
        "id": "litematica",
        "name": "Litematica",
        "slug": "litematica",
        "bundled_asset": None,
        "category": "편의",
        "required": False,
        "tags": ["편의", "건축"],
        "description": "건축 설계도(Schematic)를 게임 내에서 불러와 반투명 가이드로 표시합니다.\n정밀한 건축 작업에 필수적인 모드입니다.",
        "exclusive_group": None,
        "dependencies": [],
        "hidden": False,
    },
]

# ── 편의 조회 딕셔너리 ──────────────────────────────────────────────────
MOD_BY_ID   = {m["id"]: m for m in MODS}
VISIBLE_MODS = [m for m in MODS if not m.get("hidden", False)]
CATEGORIES  = ["전체", "필수", "최적화", "시각", "사운드", "지도", "한글", "편의"]

# ── 카테고리별 색상 (차분하게 — 모두 동일 무채색으로 시각적 구분 최소화) ──
_NEUTRAL = "#D4D4D8"
CATEGORY_COLOR = {
    "필수":  _NEUTRAL,
    "최적화": _NEUTRAL,
    "시각":  _NEUTRAL,
    "지도":  _NEUTRAL,
    "사운드": _NEUTRAL,
    "한글":  _NEUTRAL,
    "편의":  _NEUTRAL,
}
